# name: Docker image build

# on: push

# jobs:
#   build:
#     runs-on: ubuntu
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u "bhavyadhiman" --password-stdin

#       - name: Build and Push Docker Image
#         run: |
#           docker build -t bhavyadhiman/fastapi-app:latest .
#           docker push bhavyadhiman/fastapi-app:latest

name: Docker image build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u "bhavyadhiman" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \   # Multi-platform support
            --push \
            -t bhavyadhiman/fastapi-app:latest .

